### PR TITLE
Fix keypress mapping

### PR DESCRIPTION
**Pull request by xzfc**
Fixed keys: `F1`..`F10`, `` ` ``, `Pause`, Numpad `+`.

Also, on some 60% keyboards ESC is called `KC_GESC`, rather than `KC_ESC`, and thus unpressable. Is this intended? Can we just unify these two keycodes into a single `KC_ESC`?

### CODE REVIEW

**Review by crsnbrt — CHANGES_REQUESTED** [review]
@xzfc The fix for the numpad and F-keys looks good, but the ` and pause are just using values from the aliases column here: https://beta.docs.qmk.fm/using-qmk/simple-keycodes/keycodes. All the keymaps use these shorthand alias values when they are available for example: https://github.com/crsnbrt/keysim/blob/175a4670b31dcc94192caf30e9a47f243cea5599/src/config/keymaps/keymap_100_default.json#L20 For now i think we should keep these as is.

**Comment by crsnbrt** [comment]
Also I agree on the ESC since there is no need to differentiate these in this tool.

**Comment by xzfc** [comment]
Do you want me to add alias support in `KeyManager` with the following config?

```js
// src/config/keys/aliases.json
{
    "KC_PAUSE": ["KC_PAUS"],
    "KC_GRAVE": ["KC_GRV", "KC_ZKHK"],
    /* and so on ... */
    
    // Also, KC_GESC could be aliased to KC_ESC
    "KC_ESC": [ "KC_GESC", "GRAVE_ESC" ]
}
```

**Comment by crsnbrt** [comment]
I don't know if there is much benefit to the extra complexity. It's probably just easier to update the keymaps to use KC_ESC and add some additional info in the readme about the aliases or something.

This could be useful longterm if there was support for custom keymaps.

**Pull request merged**
